library(readxl)
X50_Startups <- read_excel("E:/kamagyana/Computing/DARET/Assignments/50_Startups.xlsx")
View(X50_Startups)
library(dplyr)
library(sqldf)
library(ggplot2)
library(car)
library(mice)
library(Hmisc)
library(stats)
library(car)
nustart <- X50_Startups %>% select("R&D Spend", "Administration", "Marketing Spend", "Profit")
options(digits=10)
head(numstart)
summary(numstart)
rcorr(numstart)
str(numstart)
numstart <- as.matrix(numstart)
rcorr(numstart)
trsize <- floor(0.75 * nrow(X50_Startups))
set.seed(123)
trdata <- sample(seq_len(nrow(X50_Startups)), size = trsize)
train <- X50_Startups[trdata,]
test<- X50_Startups[-trdata,]
Starup <- mutate(X50_Startups,DONE = ifelse(X50_Startups$State == "Florida",1,0))
Starup <- mutate(Starup,DTWO = ifelse(Starup$State == "New York",1,0))head(Starup)
head(Starup)
Starup <- as.data.frame(Starup)
regresuls <- lm(Starup$Profit ~ Starup$'r&dspend'+Starup$Administration+Starup$MarketingSpend+Starup$DONE+Starup$DTWO)
summary(regresuls)
vif(regresuls)
regresuls1 <- lm(Starup$Profit ~ Starup$'r&dspend'+Starup$Administration+Starup$MarketingSpend)
summary(regresuls1)
regresuls2 <- lm(Starup$Profit ~ Starup$'r&dspend'+ Starup$MarketingSpend)
summary(regresuls2)
plot(regresuls$fitted.values, regresuls$residuals)
plot(regresuls1$fitted.values, regresuls1$residuals)
plot(regresuls2$fitted.values, regresuls2$residuals)
trsize <- floor(0.75 * nrow(Starup))
set.seed(123)
trdata <- sample(seq_len(nrow(Starup)), size = trsize)
train <- X50_Startups[trdata,]
test<- X50_Startups[-trdata,]
trainreg <- lm(train$Profit ~ train$'r&dspend'+ train$MarketingSpend)
summary(trainreg)
head(test)
library(dplyr)
test <- mutate(test, preprofit = (48930 + 0.8085*(test$'r&dspend')) )
head(test)
library(ggplot2)
test <- mutate(test, prederror = (test$Profit - test$preprofit))
plot(test$prederror)
library(stats)
shapiro.test(x = test$prederror)
test$sno <- 1:nrow(test)
head(test)
ggplot(test,aes(x = sno)) + geom_line(aes(y = Profit, colour = "Profit")) + geom_line(aes(y = preprofit, colour = "preprofit")) + scale_colour_manual("", breaks = c("Profit","preprofit"), values = c("red","blue")) + ylab(label = "Profit") + xlab(label = "sno")

